/* colorThemes */

export const colorThemes = {
  'default': {

    fontFamily: 'inherit',
    fontSize: 'inherit',
    positionLeft: '46%',
    smallBreakPoint: '576',
    mediumBreakPoint: '992',
    buttonTextColor: '#13294B',
    buttonBackgroundColor: '#dddddd',
    focusBorderColor: '#C5050C',
    menuTextColor: '#13294B',
    menuBackgroundColor: '#dddddd',
    menuitemFocusTextColor: '#dddddd',
    menuitemFocusBackgroundColor: '#13294B',
    zIndex: '10000',
    zHighlight: '9000',
    displayOption: 'fixed'
  },
  'aria': {
    hostnameSelector: 'w3.org',
    pathnameSelector: 'ARIA/apg',
    fontFamily: 'sans-serif',
    fontSize: '10pt',
    positionLeft: '7%',
    menuTextColor: '#000',
    menuBackgroundColor: '#def',
    menuitemFocusTextColor: '#fff',
    menuitemFocusBackgroundColor: '#005a9c',
    focusBorderColor: '#005a9c',
    buttonTextColor: '#005a9c',
    buttonBackgroundColor: '#ddd',
  },
  'illinois': {
    hostnameSelector: 'illinois.edu',
    menuTextColor: '#00132c',
    menuBackgroundColor: '#cad9ef',
    menuitemFocusTextColor: '#eeeeee',
    menuitemFocusBackgroundColor: '#00132c',
    focusBorderColor: '#ff552e',
    buttonTextColor: '#444444',
    buttonBackgroundColor: '#dddede',
  },
  'openweba11y': {
    hostnameSelector: 'openweba11y.com',
    buttonTextColor: '#13294B',
    buttonBackgroundColor: '#dddddd',
    focusBorderColor: '#C5050C',
    menuTextColor: '#13294B',
    menuBackgroundColor: '#dddddd',
    menuitemFocusTextColor: '#dddddd',
    menuitemFocusBackgroundColor: '#13294B',
    fontSize: '90%'
  },
  'skipto': {
    hostnameSelector: 'skipto-landmarks-headings.github.io',
    positionLeft: '25%',
    fontSize: '14px',
    menuTextColor: '#00132c',
    menuBackgroundColor: '#cad9ef',
    menuitemFocusTextColor: '#eeeeee',
    menuitemFocusBackgroundColor: '#00132c',
    focusBorderColor: '#ff552e',
    buttonTextColor: '#444444',
    buttonBackgroundColor: '#dddede',
  },
  'uic': {
    hostnameSelector: 'uic.edu',
    menuTextColor: '#001e62',
    menuBackgroundColor: '#f8f8f8',
    menuitemFocusTextColor: '#ffffff',
    menuitemFocusBackgroundColor: '#001e62',
    focusBorderColor: '#d50032',
    buttonTextColor: '#ffffff',
    buttonBackgroundColor: '#001e62',
  },
  'uillinois': {
    hostnameSelector: 'uillinois.edu',
    menuTextColor: '#001e62',
    menuBackgroundColor: '#e8e9ea',
    menuitemFocusTextColor: '#f8f8f8',
    menuitemFocusBackgroundColor: '#13294b',
    focusBorderColor: '#dd3403',
    buttonTextColor: '#e8e9ea',
    buttonBackgroundColor: '#13294b',
  },
  'uis': {
    hostnameSelector: 'uis.edu',
    menuTextColor: '#036',
    menuBackgroundColor: '#fff',
    menuitemFocusTextColor: '#fff',
    menuitemFocusBackgroundColor: '#036',
    focusBorderColor: '#dd3444',
    buttonTextColor: '#fff',
    buttonBackgroundColor: '#036',
  },
  'walmart': {
    hostnameSelector: 'walmart.com',
    buttonTextColor: '#ffffff',
    buttonBackgroundColor: '#00419a',
    focusBorderColor: '#ffc220',
    menuTextColor: '#ffffff',
    menuBackgroundColor: '#0071dc',
    menuitemFocusTextColor: '#00419a',
    menuitemFocusBackgroundColor: '#ffffff',
  }
};
